{% set name = "idds-workflow" %}
{% set name_pypi = "idds_workflow" %}
{% set version = "2.6.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name_pypi }}/{{ name_pypi }}-{{ version }}.tar.gz
  sha256: ae7d9ebe2968f6a6929cb66758ebd40efdde150adb645b145c7577f78140c444


build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - idds-common =={{ version }}
    - python >={{ python_min }}
    - stomp.py

test:
  requires:
    - python {{ python_min }}
  imports:
    - idds
    - idds.workflow

about:
  home: https://pypi.org/project/idds-workflow/
  license: Apache-2.0
  license_file: LICENSE.rst
  summary: intelligent Data Delivery Service(iDDS) Package
  doc_url: https://idds.readthedocs.io/en/latest/
  dev_url: https://github.com/HSF/iDDS

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
